### PR TITLE
Mention dotenv-safe in README

### PR DESCRIPTION
**Pull request by rolodato**
Disclaimer: I'm the owner/maintainer of dotenv-safe. Figured it was worth mentioning since `.env.example` was already mentioned as a best practice here.

### CODE REVIEW

**Comment by vpanjganj** [comment]
Hi, I think using this library is unnecessary. Our approach (has not yet included in the document) is to use minimum number of dependencies.
Thanks for the PR

**Comment by rolodato** [comment]
@vpanjganj Thanks for the clarification. I think it would make sense to at least mention `dotenv` in there. The recommendation is to use `.env`/`.env.example` files, but it doesn't mention how those files are structured or how to read them.

**Comment by vpanjganj** [comment]
You're right. Do you think you have time make a pull request to cover those? If not I will do.

**Comment by rolodato** [comment]
@vpanjganj Not today. Feel free to take a stab at it if you have time. FWIW I still think it makes sense to mention dotenv-safe if we're recommending `.env.example` as a best practice, since it provides more benefits than plain dotenv without any additional work in that case. Thanks!

**Pull request closed without merging**
