### PR TITLE
Fixed camelCase / PascalCase typo.

### PR DESCRIPTION
**Pull request by moltar**
Not sure if the actual content was meant to be this way (I just assumed). But there was a syntax problem / typo.

### CODE REVIEW

**Comment by moltar** [comment]
So should it be `PascalCase/cameCase.js` then?

**Comment by moltar** [comment]
Also, the page does not mention React anywhere in the README. I wasn't under assumption this was React-specific guideline. I think it should be generic for all JS projects, and add specificity, if necessary, clearly marking as so.

I don't think there is an established convention to use CamelCase for folder names for anything other than React components.

**Comment by vpanjganj** [comment]
In that case the bulletpoint after it should go as well. This was meant for internal use initially, and we mostly use react. But you’re also right about it being irrelevant. So let’s ditch them.

**Comment by moltar** [comment]
Removed React-specific naming conventions.

Although, it'd be useful to have naming conventions overall.

**Pull request merged**
