### PR TITLE
Add description about squash commits

### PR DESCRIPTION
**Pull request by Aleyasen**
Add description about squash commits before rebasing to develop branch.

### CODE REVIEW

**Comment by vpanjganj** [comment]
Thanks for your PR, it would be great if you add a link or ideally if possible  add a command sample.

**Comment by Aleyasen** [comment]
Thanks @vpanjganj . I added a link for squashing commits in interactive rebase.

**Comment by gyg3** [comment]
Xf

**Comment by vpanjganj** [comment]
Hi,
I was thinking if it is better to promote `--autosquash` instead. Also to keep the link relevant we can use [this link](https://robots.thoughtbot.com/autosquashing-git-commits) instead. So it will read like:
> You can use `--autosquash` to [squash all your commits to a single commit](https://robots.thoughtbot.com/autosquashing-git-commits). Nobody wants many commits for a single feature in develop branch! 

```
git checkout <branchname>
git rebase -i --autosquash develop
...
```
What do you think ? 
:) واقعا شرمنده

**Comment by vpanjganj** [comment]
I added `--autosquash`

**Pull request closed without merging**
